// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "time"

type AuditdLinux struct {
	// Timestamp corresponds to the JSON schema field "@timestamp".
	Timestamp *time.Time `json:"@timestamp,omitempty" yaml:"@timestamp,omitempty" mapstructure:"@timestamp,omitempty"`

	// Version corresponds to the JSON schema field "@version".
	Version *string `json:"@version,omitempty" yaml:"@version,omitempty" mapstructure:"@version,omitempty"`

	// Id corresponds to the JSON schema field "_id".
	Id *string `json:"_id,omitempty" yaml:"_id,omitempty" mapstructure:"_id,omitempty"`

	// Index corresponds to the JSON schema field "_index".
	Index *string `json:"_index,omitempty" yaml:"_index,omitempty" mapstructure:"_index,omitempty"`

	// Account corresponds to the JSON schema field "account".
	Account *string `json:"account,omitempty" yaml:"account,omitempty" mapstructure:"account,omitempty"`

	// ActualUser corresponds to the JSON schema field "actual_user".
	ActualUser *string `json:"actual_user,omitempty" yaml:"actual_user,omitempty" mapstructure:"actual_user,omitempty"`

	// Args corresponds to the JSON schema field "args".
	Args *string `json:"args,omitempty" yaml:"args,omitempty" mapstructure:"args,omitempty"`

	// Auid corresponds to the JSON schema field "auid".
	Auid *string `json:"auid,omitempty" yaml:"auid,omitempty" mapstructure:"auid,omitempty"`

	// Cmdline corresponds to the JSON schema field "cmdline".
	Cmdline *string `json:"cmdline,omitempty" yaml:"cmdline,omitempty" mapstructure:"cmdline,omitempty"`

	// DateDay corresponds to the JSON schema field "date_day".
	DateDay *string `json:"date_day,omitempty" yaml:"date_day,omitempty" mapstructure:"date_day,omitempty"`

	// DateHour corresponds to the JSON schema field "date_hour".
	DateHour *string `json:"date_hour,omitempty" yaml:"date_hour,omitempty" mapstructure:"date_hour,omitempty"`

	// DateMinute corresponds to the JSON schema field "date_minute".
	DateMinute *string `json:"date_minute,omitempty" yaml:"date_minute,omitempty" mapstructure:"date_minute,omitempty"`

	// DateMonth corresponds to the JSON schema field "date_month".
	DateMonth *string `json:"date_month,omitempty" yaml:"date_month,omitempty" mapstructure:"date_month,omitempty"`

	// DateSecond corresponds to the JSON schema field "date_second".
	DateSecond *string `json:"date_second,omitempty" yaml:"date_second,omitempty" mapstructure:"date_second,omitempty"`

	// DateYear corresponds to the JSON schema field "date_year".
	DateYear *string `json:"date_year,omitempty" yaml:"date_year,omitempty" mapstructure:"date_year,omitempty"`

	// EventId corresponds to the JSON schema field "event_id".
	EventId *string `json:"event_id,omitempty" yaml:"event_id,omitempty" mapstructure:"event_id,omitempty"`

	// Exe corresponds to the JSON schema field "exe".
	Exe *string `json:"exe,omitempty" yaml:"exe,omitempty" mapstructure:"exe,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *string `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty" mapstructure:"fingerprint,omitempty"`

	// HostIp corresponds to the JSON schema field "host_ip".
	HostIp *string `json:"host_ip,omitempty" yaml:"host_ip,omitempty" mapstructure:"host_ip,omitempty"`

	// HostName corresponds to the JSON schema field "host_name".
	HostName *string `json:"host_name,omitempty" yaml:"host_name,omitempty" mapstructure:"host_name,omitempty"`

	// Key corresponds to the JSON schema field "key".
	Key *string `json:"key,omitempty" yaml:"key,omitempty" mapstructure:"key,omitempty"`

	// Op corresponds to the JSON schema field "op".
	Op *string `json:"op,omitempty" yaml:"op,omitempty" mapstructure:"op,omitempty"`

	// ProcessCurrentDirectory corresponds to the JSON schema field
	// "process_current_directory".
	ProcessCurrentDirectory *string `json:"process_current_directory,omitempty" yaml:"process_current_directory,omitempty" mapstructure:"process_current_directory,omitempty"`

	// ProcessId corresponds to the JSON schema field "process_id".
	ProcessId *string `json:"process_id,omitempty" yaml:"process_id,omitempty" mapstructure:"process_id,omitempty"`

	// Proctitle corresponds to the JSON schema field "proctitle".
	Proctitle *string `json:"proctitle,omitempty" yaml:"proctitle,omitempty" mapstructure:"proctitle,omitempty"`

	// ProjectId corresponds to the JSON schema field "project_id".
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty" mapstructure:"project_id,omitempty"`

	// Res corresponds to the JSON schema field "res".
	Res *string `json:"res,omitempty" yaml:"res,omitempty" mapstructure:"res,omitempty"`

	// RuleName corresponds to the JSON schema field "rule_name".
	RuleName *string `json:"rule_name,omitempty" yaml:"rule_name,omitempty" mapstructure:"rule_name,omitempty"`

	// Success corresponds to the JSON schema field "success".
	Success *string `json:"success,omitempty" yaml:"success,omitempty" mapstructure:"success,omitempty"`

	// Syscall corresponds to the JSON schema field "syscall".
	Syscall *string `json:"syscall,omitempty" yaml:"syscall,omitempty" mapstructure:"syscall,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TargetId corresponds to the JSON schema field "target_id".
	TargetId *string `json:"target_id,omitempty" yaml:"target_id,omitempty" mapstructure:"target_id,omitempty"`

	// TargetIdName corresponds to the JSON schema field "target_id_name".
	TargetIdName *string `json:"target_id_name,omitempty" yaml:"target_id_name,omitempty" mapstructure:"target_id_name,omitempty"`

	// Terminal corresponds to the JSON schema field "terminal".
	Terminal *string `json:"terminal,omitempty" yaml:"terminal,omitempty" mapstructure:"terminal,omitempty"`

	// Uid corresponds to the JSON schema field "uid".
	Uid *string `json:"uid,omitempty" yaml:"uid,omitempty" mapstructure:"uid,omitempty"`

	// User corresponds to the JSON schema field "user".
	User *string `json:"user,omitempty" yaml:"user,omitempty" mapstructure:"user,omitempty"`
}
