// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "time"

type Ips struct {
	// Timestamp corresponds to the JSON schema field "@timestamp".
	Timestamp *time.Time `json:"@timestamp,omitempty" yaml:"@timestamp,omitempty" mapstructure:"@timestamp,omitempty"`

	// Version corresponds to the JSON schema field "@version".
	Version *string `json:"@version,omitempty" yaml:"@version,omitempty" mapstructure:"@version,omitempty"`

	// Id corresponds to the JSON schema field "_id".
	Id *string `json:"_id,omitempty" yaml:"_id,omitempty" mapstructure:"_id,omitempty"`

	// Index corresponds to the JSON schema field "_index".
	Index *string `json:"_index,omitempty" yaml:"_index,omitempty" mapstructure:"_index,omitempty"`

	// Act corresponds to the JSON schema field "act".
	Act *string `json:"act,omitempty" yaml:"act,omitempty" mapstructure:"act,omitempty"`

	// Action corresponds to the JSON schema field "action".
	Action *string `json:"action,omitempty" yaml:"action,omitempty" mapstructure:"action,omitempty"`

	// App corresponds to the JSON schema field "app".
	App *string `json:"app,omitempty" yaml:"app,omitempty" mapstructure:"app,omitempty"`

	// Category corresponds to the JSON schema field "category".
	Category *string `json:"category,omitempty" yaml:"category,omitempty" mapstructure:"category,omitempty"`

	// DateDay corresponds to the JSON schema field "date_day".
	DateDay *string `json:"date_day,omitempty" yaml:"date_day,omitempty" mapstructure:"date_day,omitempty"`

	// DateHour corresponds to the JSON schema field "date_hour".
	DateHour *string `json:"date_hour,omitempty" yaml:"date_hour,omitempty" mapstructure:"date_hour,omitempty"`

	// DateMinute corresponds to the JSON schema field "date_minute".
	DateMinute *string `json:"date_minute,omitempty" yaml:"date_minute,omitempty" mapstructure:"date_minute,omitempty"`

	// DateMonth corresponds to the JSON schema field "date_month".
	DateMonth *string `json:"date_month,omitempty" yaml:"date_month,omitempty" mapstructure:"date_month,omitempty"`

	// DateSecond corresponds to the JSON schema field "date_second".
	DateSecond *string `json:"date_second,omitempty" yaml:"date_second,omitempty" mapstructure:"date_second,omitempty"`

	// DateYear corresponds to the JSON schema field "date_year".
	DateYear *string `json:"date_year,omitempty" yaml:"date_year,omitempty" mapstructure:"date_year,omitempty"`

	// Dest corresponds to the JSON schema field "dest".
	Dest *string `json:"dest,omitempty" yaml:"dest,omitempty" mapstructure:"dest,omitempty"`

	// DestAsName corresponds to the JSON schema field "dest_as_name".
	DestAsName *string `json:"dest_as_name,omitempty" yaml:"dest_as_name,omitempty" mapstructure:"dest_as_name,omitempty"`

	// DestAsn corresponds to the JSON schema field "dest_asn".
	DestAsn *string `json:"dest_asn,omitempty" yaml:"dest_asn,omitempty" mapstructure:"dest_asn,omitempty"`

	// DestCountry corresponds to the JSON schema field "dest_country".
	DestCountry *string `json:"dest_country,omitempty" yaml:"dest_country,omitempty" mapstructure:"dest_country,omitempty"`

	// DestPort corresponds to the JSON schema field "dest_port".
	DestPort *string `json:"dest_port,omitempty" yaml:"dest_port,omitempty" mapstructure:"dest_port,omitempty"`

	// Domain corresponds to the JSON schema field "domain".
	Domain *string `json:"domain,omitempty" yaml:"domain,omitempty" mapstructure:"domain,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *string `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty" mapstructure:"fingerprint,omitempty"`

	// HostIp corresponds to the JSON schema field "host_ip".
	HostIp *string `json:"host_ip,omitempty" yaml:"host_ip,omitempty" mapstructure:"host_ip,omitempty"`

	// HostName corresponds to the JSON schema field "host_name".
	HostName *string `json:"host_name,omitempty" yaml:"host_name,omitempty" mapstructure:"host_name,omitempty"`

	// ProjectId corresponds to the JSON schema field "project_id".
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty" mapstructure:"project_id,omitempty"`

	// SessionId corresponds to the JSON schema field "session_id".
	SessionId *string `json:"session_id,omitempty" yaml:"session_id,omitempty" mapstructure:"session_id,omitempty"`

	// Severity corresponds to the JSON schema field "severity".
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`

	// Signature corresponds to the JSON schema field "signature".
	Signature *string `json:"signature,omitempty" yaml:"signature,omitempty" mapstructure:"signature,omitempty"`

	// Src corresponds to the JSON schema field "src".
	Src *string `json:"src,omitempty" yaml:"src,omitempty" mapstructure:"src,omitempty"`

	// SrcAsName corresponds to the JSON schema field "src_as_name".
	SrcAsName *string `json:"src_as_name,omitempty" yaml:"src_as_name,omitempty" mapstructure:"src_as_name,omitempty"`

	// SrcAsn corresponds to the JSON schema field "src_asn".
	SrcAsn *string `json:"src_asn,omitempty" yaml:"src_asn,omitempty" mapstructure:"src_asn,omitempty"`

	// SrcCountry corresponds to the JSON schema field "src_country".
	SrcCountry *string `json:"src_country,omitempty" yaml:"src_country,omitempty" mapstructure:"src_country,omitempty"`

	// SrcPort corresponds to the JSON schema field "src_port".
	SrcPort *string `json:"src_port,omitempty" yaml:"src_port,omitempty" mapstructure:"src_port,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// UriPath corresponds to the JSON schema field "uri_path".
	UriPath *string `json:"uri_path,omitempty" yaml:"uri_path,omitempty" mapstructure:"uri_path,omitempty"`

	// UriQuery corresponds to the JSON schema field "uri_query".
	UriQuery *string `json:"uri_query,omitempty" yaml:"uri_query,omitempty" mapstructure:"uri_query,omitempty"`

	// UserAgent corresponds to the JSON schema field "user_agent".
	UserAgent *string `json:"user_agent,omitempty" yaml:"user_agent,omitempty" mapstructure:"user_agent,omitempty"`

	// VendorProduct corresponds to the JSON schema field "vendor_product".
	VendorProduct *string `json:"vendor_product,omitempty" yaml:"vendor_product,omitempty" mapstructure:"vendor_product,omitempty"`
}
