// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

type SysmonWindows struct {
	// Timestamp corresponds to the JSON schema field "@timestamp".
	Timestamp *string `json:"@timestamp,omitempty" yaml:"@timestamp,omitempty" mapstructure:"@timestamp,omitempty"`

	// Version corresponds to the JSON schema field "@version".
	Version *string `json:"@version,omitempty" yaml:"@version,omitempty" mapstructure:"@version,omitempty"`

	// Id corresponds to the JSON schema field "_id".
	Id *string `json:"_id,omitempty" yaml:"_id,omitempty" mapstructure:"_id,omitempty"`

	// Index corresponds to the JSON schema field "_index".
	Index *string `json:"_index,omitempty" yaml:"_index,omitempty" mapstructure:"_index,omitempty"`

	// Cmdline corresponds to the JSON schema field "cmdline".
	Cmdline *string `json:"cmdline,omitempty" yaml:"cmdline,omitempty" mapstructure:"cmdline,omitempty"`

	// DateDay corresponds to the JSON schema field "date_day".
	DateDay *string `json:"date_day,omitempty" yaml:"date_day,omitempty" mapstructure:"date_day,omitempty"`

	// DateHour corresponds to the JSON schema field "date_hour".
	DateHour *string `json:"date_hour,omitempty" yaml:"date_hour,omitempty" mapstructure:"date_hour,omitempty"`

	// DateMinute corresponds to the JSON schema field "date_minute".
	DateMinute *string `json:"date_minute,omitempty" yaml:"date_minute,omitempty" mapstructure:"date_minute,omitempty"`

	// DateMonth corresponds to the JSON schema field "date_month".
	DateMonth *string `json:"date_month,omitempty" yaml:"date_month,omitempty" mapstructure:"date_month,omitempty"`

	// DateSecond corresponds to the JSON schema field "date_second".
	DateSecond *string `json:"date_second,omitempty" yaml:"date_second,omitempty" mapstructure:"date_second,omitempty"`

	// DateYear corresponds to the JSON schema field "date_year".
	DateYear *string `json:"date_year,omitempty" yaml:"date_year,omitempty" mapstructure:"date_year,omitempty"`

	// EventId corresponds to the JSON schema field "event_id".
	EventId *string `json:"event_id,omitempty" yaml:"event_id,omitempty" mapstructure:"event_id,omitempty"`

	// FileName corresponds to the JSON schema field "file_name".
	FileName *string `json:"file_name,omitempty" yaml:"file_name,omitempty" mapstructure:"file_name,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *string `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty" mapstructure:"fingerprint,omitempty"`

	// HashesImphash corresponds to the JSON schema field "hashes_imphash".
	HashesImphash *string `json:"hashes_imphash,omitempty" yaml:"hashes_imphash,omitempty" mapstructure:"hashes_imphash,omitempty"`

	// HashesMd5 corresponds to the JSON schema field "hashes_md5".
	HashesMd5 *string `json:"hashes_md5,omitempty" yaml:"hashes_md5,omitempty" mapstructure:"hashes_md5,omitempty"`

	// HashesSha1 corresponds to the JSON schema field "hashes_sha1".
	HashesSha1 *string `json:"hashes_sha1,omitempty" yaml:"hashes_sha1,omitempty" mapstructure:"hashes_sha1,omitempty"`

	// HashesSha256 corresponds to the JSON schema field "hashes_sha256".
	HashesSha256 *string `json:"hashes_sha256,omitempty" yaml:"hashes_sha256,omitempty" mapstructure:"hashes_sha256,omitempty"`

	// HostIp corresponds to the JSON schema field "host_ip".
	HostIp *string `json:"host_ip,omitempty" yaml:"host_ip,omitempty" mapstructure:"host_ip,omitempty"`

	// HostName corresponds to the JSON schema field "host_name".
	HostName *string `json:"host_name,omitempty" yaml:"host_name,omitempty" mapstructure:"host_name,omitempty"`

	// OriginalFileName corresponds to the JSON schema field "original_file_name".
	OriginalFileName *string `json:"original_file_name,omitempty" yaml:"original_file_name,omitempty" mapstructure:"original_file_name,omitempty"`

	// ParentCmdline corresponds to the JSON schema field "parent_cmdline".
	ParentCmdline *string `json:"parent_cmdline,omitempty" yaml:"parent_cmdline,omitempty" mapstructure:"parent_cmdline,omitempty"`

	// ParentName corresponds to the JSON schema field "parent_name".
	ParentName *string `json:"parent_name,omitempty" yaml:"parent_name,omitempty" mapstructure:"parent_name,omitempty"`

	// ParentProcessPath corresponds to the JSON schema field "parent_process_path".
	ParentProcessPath *string `json:"parent_process_path,omitempty" yaml:"parent_process_path,omitempty" mapstructure:"parent_process_path,omitempty"`

	// ParentUser corresponds to the JSON schema field "parent_user".
	ParentUser *string `json:"parent_user,omitempty" yaml:"parent_user,omitempty" mapstructure:"parent_user,omitempty"`

	// ProcessCurrentDirectory corresponds to the JSON schema field
	// "process_current_directory".
	ProcessCurrentDirectory *string `json:"process_current_directory,omitempty" yaml:"process_current_directory,omitempty" mapstructure:"process_current_directory,omitempty"`

	// ProcessId corresponds to the JSON schema field "process_id".
	ProcessId *string `json:"process_id,omitempty" yaml:"process_id,omitempty" mapstructure:"process_id,omitempty"`

	// ProcessName corresponds to the JSON schema field "process_name".
	ProcessName *string `json:"process_name,omitempty" yaml:"process_name,omitempty" mapstructure:"process_name,omitempty"`

	// ProcessPath corresponds to the JSON schema field "process_path".
	ProcessPath *string `json:"process_path,omitempty" yaml:"process_path,omitempty" mapstructure:"process_path,omitempty"`

	// ProjectId corresponds to the JSON schema field "project_id".
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty" mapstructure:"project_id,omitempty"`

	// RuleName corresponds to the JSON schema field "rule_name".
	RuleName *string `json:"rule_name,omitempty" yaml:"rule_name,omitempty" mapstructure:"rule_name,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// User corresponds to the JSON schema field "user".
	User *string `json:"user,omitempty" yaml:"user,omitempty" mapstructure:"user,omitempty"`
}
