// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

type WebApplicationFirewall struct {
	// Timestamp corresponds to the JSON schema field "@timestamp".
	Timestamp *string `json:"@timestamp,omitempty" yaml:"@timestamp,omitempty" mapstructure:"@timestamp,omitempty"`

	// Version corresponds to the JSON schema field "@version".
	Version *string `json:"@version,omitempty" yaml:"@version,omitempty" mapstructure:"@version,omitempty"`

	// Id corresponds to the JSON schema field "_id".
	Id *string `json:"_id,omitempty" yaml:"_id,omitempty" mapstructure:"_id,omitempty"`

	// Index corresponds to the JSON schema field "_index".
	Index *string `json:"_index,omitempty" yaml:"_index,omitempty" mapstructure:"_index,omitempty"`

	// Action corresponds to the JSON schema field "action".
	Action *string `json:"action,omitempty" yaml:"action,omitempty" mapstructure:"action,omitempty"`

	// App corresponds to the JSON schema field "app".
	App *string `json:"app,omitempty" yaml:"app,omitempty" mapstructure:"app,omitempty"`

	// BodyBytesOut corresponds to the JSON schema field "body_bytes_out".
	BodyBytesOut *string `json:"body_bytes_out,omitempty" yaml:"body_bytes_out,omitempty" mapstructure:"body_bytes_out,omitempty"`

	// BytesIn corresponds to the JSON schema field "bytes_in".
	BytesIn *string `json:"bytes_in,omitempty" yaml:"bytes_in,omitempty" mapstructure:"bytes_in,omitempty"`

	// BytesOut corresponds to the JSON schema field "bytes_out".
	BytesOut *string `json:"bytes_out,omitempty" yaml:"bytes_out,omitempty" mapstructure:"bytes_out,omitempty"`

	// Category corresponds to the JSON schema field "category".
	Category *string `json:"category,omitempty" yaml:"category,omitempty" mapstructure:"category,omitempty"`

	// Cookie corresponds to the JSON schema field "cookie".
	Cookie *string `json:"cookie,omitempty" yaml:"cookie,omitempty" mapstructure:"cookie,omitempty"`

	// DateDay corresponds to the JSON schema field "date_day".
	DateDay *string `json:"date_day,omitempty" yaml:"date_day,omitempty" mapstructure:"date_day,omitempty"`

	// DateHour corresponds to the JSON schema field "date_hour".
	DateHour *string `json:"date_hour,omitempty" yaml:"date_hour,omitempty" mapstructure:"date_hour,omitempty"`

	// DateMinute corresponds to the JSON schema field "date_minute".
	DateMinute *string `json:"date_minute,omitempty" yaml:"date_minute,omitempty" mapstructure:"date_minute,omitempty"`

	// DateMonth corresponds to the JSON schema field "date_month".
	DateMonth *string `json:"date_month,omitempty" yaml:"date_month,omitempty" mapstructure:"date_month,omitempty"`

	// DateSecond corresponds to the JSON schema field "date_second".
	DateSecond *string `json:"date_second,omitempty" yaml:"date_second,omitempty" mapstructure:"date_second,omitempty"`

	// DateYear corresponds to the JSON schema field "date_year".
	DateYear *string `json:"date_year,omitempty" yaml:"date_year,omitempty" mapstructure:"date_year,omitempty"`

	// Dest corresponds to the JSON schema field "dest".
	Dest *string `json:"dest,omitempty" yaml:"dest,omitempty" mapstructure:"dest,omitempty"`

	// DestAsName corresponds to the JSON schema field "dest_as_name".
	DestAsName *string `json:"dest_as_name,omitempty" yaml:"dest_as_name,omitempty" mapstructure:"dest_as_name,omitempty"`

	// DestAsn corresponds to the JSON schema field "dest_asn".
	DestAsn *string `json:"dest_asn,omitempty" yaml:"dest_asn,omitempty" mapstructure:"dest_asn,omitempty"`

	// DestCountry corresponds to the JSON schema field "dest_country".
	DestCountry *string `json:"dest_country,omitempty" yaml:"dest_country,omitempty" mapstructure:"dest_country,omitempty"`

	// DestPort corresponds to the JSON schema field "dest_port".
	DestPort *string `json:"dest_port,omitempty" yaml:"dest_port,omitempty" mapstructure:"dest_port,omitempty"`

	// Duration corresponds to the JSON schema field "duration".
	Duration *string `json:"duration,omitempty" yaml:"duration,omitempty" mapstructure:"duration,omitempty"`

	// FileExtension corresponds to the JSON schema field "file_extension".
	FileExtension *string `json:"file_extension,omitempty" yaml:"file_extension,omitempty" mapstructure:"file_extension,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *string `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty" mapstructure:"fingerprint,omitempty"`

	// FullRequest corresponds to the JSON schema field "full_request".
	FullRequest *string `json:"full_request,omitempty" yaml:"full_request,omitempty" mapstructure:"full_request,omitempty"`

	// Host corresponds to the JSON schema field "host".
	Host *string `json:"host,omitempty" yaml:"host,omitempty" mapstructure:"host,omitempty"`

	// HostIp corresponds to the JSON schema field "host_ip".
	HostIp *string `json:"host_ip,omitempty" yaml:"host_ip,omitempty" mapstructure:"host_ip,omitempty"`

	// HostName corresponds to the JSON schema field "host_name".
	HostName *string `json:"host_name,omitempty" yaml:"host_name,omitempty" mapstructure:"host_name,omitempty"`

	// HttpClassName corresponds to the JSON schema field "http_class_name".
	HttpClassName *string `json:"http_class_name,omitempty" yaml:"http_class_name,omitempty" mapstructure:"http_class_name,omitempty"`

	// HttpMethod corresponds to the JSON schema field "http_method".
	HttpMethod *string `json:"http_method,omitempty" yaml:"http_method,omitempty" mapstructure:"http_method,omitempty"`

	// HttpReferrer corresponds to the JSON schema field "http_referrer".
	HttpReferrer *string `json:"http_referrer,omitempty" yaml:"http_referrer,omitempty" mapstructure:"http_referrer,omitempty"`

	// HttpReferrerDomain corresponds to the JSON schema field "http_referrer_domain".
	HttpReferrerDomain *string `json:"http_referrer_domain,omitempty" yaml:"http_referrer_domain,omitempty" mapstructure:"http_referrer_domain,omitempty"`

	// HttpUserAgent corresponds to the JSON schema field "http_user_agent".
	HttpUserAgent *string `json:"http_user_agent,omitempty" yaml:"http_user_agent,omitempty" mapstructure:"http_user_agent,omitempty"`

	// OriginalSrc corresponds to the JSON schema field "original_src".
	OriginalSrc *string `json:"original_src,omitempty" yaml:"original_src,omitempty" mapstructure:"original_src,omitempty"`

	// OriginalSrcAsName corresponds to the JSON schema field "original_src_as_name".
	OriginalSrcAsName *string `json:"original_src_as_name,omitempty" yaml:"original_src_as_name,omitempty" mapstructure:"original_src_as_name,omitempty"`

	// OriginalSrcAsn corresponds to the JSON schema field "original_src_asn".
	OriginalSrcAsn *string `json:"original_src_asn,omitempty" yaml:"original_src_asn,omitempty" mapstructure:"original_src_asn,omitempty"`

	// OriginalSrcCountry corresponds to the JSON schema field "original_src_country".
	OriginalSrcCountry *string `json:"original_src_country,omitempty" yaml:"original_src_country,omitempty" mapstructure:"original_src_country,omitempty"`

	// PolicyName corresponds to the JSON schema field "policy_name".
	PolicyName *string `json:"policy_name,omitempty" yaml:"policy_name,omitempty" mapstructure:"policy_name,omitempty"`

	// ProjectId corresponds to the JSON schema field "project_id".
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty" mapstructure:"project_id,omitempty"`

	// Realip corresponds to the JSON schema field "realip".
	Realip *string `json:"realip,omitempty" yaml:"realip,omitempty" mapstructure:"realip,omitempty"`

	// RealipAsName corresponds to the JSON schema field "realip_as_name".
	RealipAsName *string `json:"realip_as_name,omitempty" yaml:"realip_as_name,omitempty" mapstructure:"realip_as_name,omitempty"`

	// RealipAsn corresponds to the JSON schema field "realip_asn".
	RealipAsn *string `json:"realip_asn,omitempty" yaml:"realip_asn,omitempty" mapstructure:"realip_asn,omitempty"`

	// RealipCountry corresponds to the JSON schema field "realip_country".
	RealipCountry *string `json:"realip_country,omitempty" yaml:"realip_country,omitempty" mapstructure:"realip_country,omitempty"`

	// Referer corresponds to the JSON schema field "referer".
	Referer *string `json:"referer,omitempty" yaml:"referer,omitempty" mapstructure:"referer,omitempty"`

	// SendContentType corresponds to the JSON schema field "send_content_type".
	SendContentType *string `json:"send_content_type,omitempty" yaml:"send_content_type,omitempty" mapstructure:"send_content_type,omitempty"`

	// Severity corresponds to the JSON schema field "severity".
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`

	// Signature corresponds to the JSON schema field "signature".
	Signature *string `json:"signature,omitempty" yaml:"signature,omitempty" mapstructure:"signature,omitempty"`

	// Site corresponds to the JSON schema field "site".
	Site *string `json:"site,omitempty" yaml:"site,omitempty" mapstructure:"site,omitempty"`

	// Src corresponds to the JSON schema field "src".
	Src *string `json:"src,omitempty" yaml:"src,omitempty" mapstructure:"src,omitempty"`

	// SrcAsName corresponds to the JSON schema field "src_as_name".
	SrcAsName *string `json:"src_as_name,omitempty" yaml:"src_as_name,omitempty" mapstructure:"src_as_name,omitempty"`

	// SrcAsn corresponds to the JSON schema field "src_asn".
	SrcAsn *string `json:"src_asn,omitempty" yaml:"src_asn,omitempty" mapstructure:"src_asn,omitempty"`

	// SrcCountry corresponds to the JSON schema field "src_country".
	SrcCountry *string `json:"src_country,omitempty" yaml:"src_country,omitempty" mapstructure:"src_country,omitempty"`

	// SrcPort corresponds to the JSON schema field "src_port".
	SrcPort *string `json:"src_port,omitempty" yaml:"src_port,omitempty" mapstructure:"src_port,omitempty"`

	// Status corresponds to the JSON schema field "status".
	Status *string `json:"status,omitempty" yaml:"status,omitempty" mapstructure:"status,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags *string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// UriPath corresponds to the JSON schema field "uri_path".
	UriPath *string `json:"uri_path,omitempty" yaml:"uri_path,omitempty" mapstructure:"uri_path,omitempty"`

	// UriQuery corresponds to the JSON schema field "uri_query".
	UriQuery *string `json:"uri_query,omitempty" yaml:"uri_query,omitempty" mapstructure:"uri_query,omitempty"`

	// UrlDomain corresponds to the JSON schema field "url_domain".
	UrlDomain *string `json:"url_domain,omitempty" yaml:"url_domain,omitempty" mapstructure:"url_domain,omitempty"`

	// User corresponds to the JSON schema field "user".
	User *string `json:"user,omitempty" yaml:"user,omitempty" mapstructure:"user,omitempty"`

	// UserAgent corresponds to the JSON schema field "user-agent".
	UserAgent *string `json:"user-agent,omitempty" yaml:"user-agent,omitempty" mapstructure:"user-agent,omitempty"`

	// XForwardFor corresponds to the JSON schema field "x_forward_for".
	XForwardFor *string `json:"x_forward_for,omitempty" yaml:"x_forward_for,omitempty" mapstructure:"x_forward_for,omitempty"`
}
