// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

import "time"

type WindowsEventsApplication struct {
	// Timestamp corresponds to the JSON schema field "@timestamp".
	Timestamp *time.Time `json:"@timestamp,omitempty" yaml:"@timestamp,omitempty" mapstructure:"@timestamp,omitempty"`

	// Version corresponds to the JSON schema field "@version".
	Version *string `json:"@version,omitempty" yaml:"@version,omitempty" mapstructure:"@version,omitempty"`

	// Id corresponds to the JSON schema field "_id".
	Id *string `json:"_id,omitempty" yaml:"_id,omitempty" mapstructure:"_id,omitempty"`

	// Index corresponds to the JSON schema field "_index".
	Index *string `json:"_index,omitempty" yaml:"_index,omitempty" mapstructure:"_index,omitempty"`

	// ApplicationMessage corresponds to the JSON schema field "application_message".
	ApplicationMessage *string `json:"application_message,omitempty" yaml:"application_message,omitempty" mapstructure:"application_message,omitempty"`

	// DateDay corresponds to the JSON schema field "date_day".
	DateDay *string `json:"date_day,omitempty" yaml:"date_day,omitempty" mapstructure:"date_day,omitempty"`

	// DateHour corresponds to the JSON schema field "date_hour".
	DateHour *string `json:"date_hour,omitempty" yaml:"date_hour,omitempty" mapstructure:"date_hour,omitempty"`

	// DateMinute corresponds to the JSON schema field "date_minute".
	DateMinute *string `json:"date_minute,omitempty" yaml:"date_minute,omitempty" mapstructure:"date_minute,omitempty"`

	// DateMonth corresponds to the JSON schema field "date_month".
	DateMonth *string `json:"date_month,omitempty" yaml:"date_month,omitempty" mapstructure:"date_month,omitempty"`

	// DateSecond corresponds to the JSON schema field "date_second".
	DateSecond *string `json:"date_second,omitempty" yaml:"date_second,omitempty" mapstructure:"date_second,omitempty"`

	// DateYear corresponds to the JSON schema field "date_year".
	DateYear *string `json:"date_year,omitempty" yaml:"date_year,omitempty" mapstructure:"date_year,omitempty"`

	// EventCategory corresponds to the JSON schema field "event_category".
	EventCategory *string `json:"event_category,omitempty" yaml:"event_category,omitempty" mapstructure:"event_category,omitempty"`

	// EventId corresponds to the JSON schema field "event_id".
	EventId *string `json:"event_id,omitempty" yaml:"event_id,omitempty" mapstructure:"event_id,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *string `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty" mapstructure:"fingerprint,omitempty"`

	// HostIp corresponds to the JSON schema field "host_ip".
	HostIp *string `json:"host_ip,omitempty" yaml:"host_ip,omitempty" mapstructure:"host_ip,omitempty"`

	// HostName corresponds to the JSON schema field "host_name".
	HostName *string `json:"host_name,omitempty" yaml:"host_name,omitempty" mapstructure:"host_name,omitempty"`

	// ProjectId corresponds to the JSON schema field "project_id".
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty" mapstructure:"project_id,omitempty"`

	// Severity corresponds to the JSON schema field "severity".
	Severity *string `json:"severity,omitempty" yaml:"severity,omitempty" mapstructure:"severity,omitempty"`

	// SeverityValue corresponds to the JSON schema field "severity_value".
	SeverityValue *string `json:"severity_value,omitempty" yaml:"severity_value,omitempty" mapstructure:"severity_value,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`
}
