// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package types

type WindowsEventsSecurity struct {
	// Timestamp corresponds to the JSON schema field "@timestamp".
	Timestamp *string `json:"@timestamp,omitempty" yaml:"@timestamp,omitempty" mapstructure:"@timestamp,omitempty"`

	// Version corresponds to the JSON schema field "@version".
	Version *string `json:"@version,omitempty" yaml:"@version,omitempty" mapstructure:"@version,omitempty"`

	// Id corresponds to the JSON schema field "_id".
	Id *string `json:"_id,omitempty" yaml:"_id,omitempty" mapstructure:"_id,omitempty"`

	// Index corresponds to the JSON schema field "_index".
	Index *string `json:"_index,omitempty" yaml:"_index,omitempty" mapstructure:"_index,omitempty"`

	// AccountDomain corresponds to the JSON schema field "account_domain".
	AccountDomain *string `json:"account_domain,omitempty" yaml:"account_domain,omitempty" mapstructure:"account_domain,omitempty"`

	// AccountName corresponds to the JSON schema field "account_name".
	AccountName *string `json:"account_name,omitempty" yaml:"account_name,omitempty" mapstructure:"account_name,omitempty"`

	// ApplicationPath corresponds to the JSON schema field "application_path".
	ApplicationPath *string `json:"application_path,omitempty" yaml:"application_path,omitempty" mapstructure:"application_path,omitempty"`

	// Cmdline corresponds to the JSON schema field "cmdline".
	Cmdline *string `json:"cmdline,omitempty" yaml:"cmdline,omitempty" mapstructure:"cmdline,omitempty"`

	// DateDay corresponds to the JSON schema field "date_day".
	DateDay *string `json:"date_day,omitempty" yaml:"date_day,omitempty" mapstructure:"date_day,omitempty"`

	// DateHour corresponds to the JSON schema field "date_hour".
	DateHour *string `json:"date_hour,omitempty" yaml:"date_hour,omitempty" mapstructure:"date_hour,omitempty"`

	// DateMinute corresponds to the JSON schema field "date_minute".
	DateMinute *string `json:"date_minute,omitempty" yaml:"date_minute,omitempty" mapstructure:"date_minute,omitempty"`

	// DateMonth corresponds to the JSON schema field "date_month".
	DateMonth *string `json:"date_month,omitempty" yaml:"date_month,omitempty" mapstructure:"date_month,omitempty"`

	// DateSecond corresponds to the JSON schema field "date_second".
	DateSecond *string `json:"date_second,omitempty" yaml:"date_second,omitempty" mapstructure:"date_second,omitempty"`

	// DateYear corresponds to the JSON schema field "date_year".
	DateYear *string `json:"date_year,omitempty" yaml:"date_year,omitempty" mapstructure:"date_year,omitempty"`

	// EventCategory corresponds to the JSON schema field "event_category".
	EventCategory *string `json:"event_category,omitempty" yaml:"event_category,omitempty" mapstructure:"event_category,omitempty"`

	// EventId corresponds to the JSON schema field "event_id".
	EventId *string `json:"event_id,omitempty" yaml:"event_id,omitempty" mapstructure:"event_id,omitempty"`

	// Fingerprint corresponds to the JSON schema field "fingerprint".
	Fingerprint *string `json:"fingerprint,omitempty" yaml:"fingerprint,omitempty" mapstructure:"fingerprint,omitempty"`

	// HostIp corresponds to the JSON schema field "host_ip".
	HostIp *string `json:"host_ip,omitempty" yaml:"host_ip,omitempty" mapstructure:"host_ip,omitempty"`

	// HostName corresponds to the JSON schema field "host_name".
	HostName *string `json:"host_name,omitempty" yaml:"host_name,omitempty" mapstructure:"host_name,omitempty"`

	// LogonProcessName corresponds to the JSON schema field "logon_process_name".
	LogonProcessName *string `json:"logon_process_name,omitempty" yaml:"logon_process_name,omitempty" mapstructure:"logon_process_name,omitempty"`

	// LogonProcessType corresponds to the JSON schema field "logon_process_type".
	LogonProcessType *string `json:"logon_process_type,omitempty" yaml:"logon_process_type,omitempty" mapstructure:"logon_process_type,omitempty"`

	// NewProcessId corresponds to the JSON schema field "new_process_id".
	NewProcessId *string `json:"new_process_id,omitempty" yaml:"new_process_id,omitempty" mapstructure:"new_process_id,omitempty"`

	// NewProcessPath corresponds to the JSON schema field "new_process_path".
	NewProcessPath *string `json:"new_process_path,omitempty" yaml:"new_process_path,omitempty" mapstructure:"new_process_path,omitempty"`

	// ParentProcessPath corresponds to the JSON schema field "parent_process_path".
	ParentProcessPath *string `json:"parent_process_path,omitempty" yaml:"parent_process_path,omitempty" mapstructure:"parent_process_path,omitempty"`

	// ProcessId corresponds to the JSON schema field "process_id".
	ProcessId *string `json:"process_id,omitempty" yaml:"process_id,omitempty" mapstructure:"process_id,omitempty"`

	// ProcessName corresponds to the JSON schema field "process_name".
	ProcessName *string `json:"process_name,omitempty" yaml:"process_name,omitempty" mapstructure:"process_name,omitempty"`

	// ProcessPath corresponds to the JSON schema field "process_path".
	ProcessPath *string `json:"process_path,omitempty" yaml:"process_path,omitempty" mapstructure:"process_path,omitempty"`

	// ProjectId corresponds to the JSON schema field "project_id".
	ProjectId *string `json:"project_id,omitempty" yaml:"project_id,omitempty" mapstructure:"project_id,omitempty"`

	// ServiceName corresponds to the JSON schema field "service_name".
	ServiceName *string `json:"service_name,omitempty" yaml:"service_name,omitempty" mapstructure:"service_name,omitempty"`

	// ServiceStartType corresponds to the JSON schema field "service_start_type".
	ServiceStartType *string `json:"service_start_type,omitempty" yaml:"service_start_type,omitempty" mapstructure:"service_start_type,omitempty"`

	// ServiceType corresponds to the JSON schema field "service_type".
	ServiceType *string `json:"service_type,omitempty" yaml:"service_type,omitempty" mapstructure:"service_type,omitempty"`

	// Src corresponds to the JSON schema field "src".
	Src *string `json:"src,omitempty" yaml:"src,omitempty" mapstructure:"src,omitempty"`

	// SrcHostName corresponds to the JSON schema field "src_host_name".
	SrcHostName *string `json:"src_host_name,omitempty" yaml:"src_host_name,omitempty" mapstructure:"src_host_name,omitempty"`

	// Tags corresponds to the JSON schema field "tags".
	Tags []string `json:"tags,omitempty" yaml:"tags,omitempty" mapstructure:"tags,omitempty"`

	// TargetDomainName corresponds to the JSON schema field "target_domain_name".
	TargetDomainName *string `json:"target_domain_name,omitempty" yaml:"target_domain_name,omitempty" mapstructure:"target_domain_name,omitempty"`

	// User corresponds to the JSON schema field "user".
	User *string `json:"user,omitempty" yaml:"user,omitempty" mapstructure:"user,omitempty"`
}
