// Code generated by github.com/reflective-technology/cybereyes-cef/alert/codegen, DO NOT EDIT.
package alert_test

import (
	"testing"

	"github.com/reflective-technology/cybereyes-cef/alert"
	"github.com/reflective-technology/cybereyes-cef/types"
	"github.com/stretchr/testify/assert"
)

var testAuditdLinuxAlert = alert.AuditdLinuxAlert{
	AlertMetaField: testAlertMeta,
	AuditdLinuxFields: types.AuditdLinux{
		Args:                    new("test-value"),
		Exe:                     new("test-value"),
		ProcessId:               new("test-value"),
		Proctitle:               new("test-value"),
		Uid:                     new("test-value"),
		User:                    new("test-value"),
		Timestamp:               new("test-value"),
		Version:                 new("test-value"),
		Id:                      new("test-value"),
		Index:                   new("test-value"),
		Account:                 new("test-value"),
		ActualUser:              new("test-value"),
		Auid:                    new("test-value"),
		Cmdline:                 new("test-value"),
		DateDay:                 new("test-value"),
		DateHour:                new("test-value"),
		DateMinute:              new("test-value"),
		DateMonth:               new("test-value"),
		DateSecond:              new("test-value"),
		DateYear:                new("test-value"),
		EventId:                 new("test-value"),
		Fingerprint:             new("test-value"),
		HostIp:                  new("test-value"),
		HostName:                new("test-value"),
		Key:                     new("test-value"),
		Op:                      new("test-value"),
		ProcessCurrentDirectory: new("test-value"),
		ProjectId:               new("test-value"),
		Res:                     new("test-value"),
		RuleName:                new("test-value"),
		Success:                 new("test-value"),
		Syscall:                 new("test-value"),
		TargetId:                new("test-value"),
		TargetIdName:            new("test-value"),
		Terminal:                new("test-value"),
	},
}

func TestAuditdLinuxAlert_ToCef(t *testing.T) {
	cef, err := testAuditdLinuxAlert.ToCef(alert.ToCefParam{
		VendorConfig: alert.VendorReflective,
		Hostname:     "example.com",
	})
	assert.NoError(t, err)
	assert.NotEmpty(t, cef)
	t.Log(cef)
}
