// Code generated by gitlab.tp.zuso.arpa/zuso-rd-team/go-pkg/events.git/alert/codegen, DO NOT EDIT.
package alert

import (
	"gitlab.tp.zuso.arpa/zuso-rd-team/go-pkg/events.git/types"
)

type IpsAlert struct {
	AlertMetaField
	IpsFields types.Ips
}

func (alert *IpsAlert) ToCef(param ToCefParam) (string, error) {
	return ResolveCef(
		alert.AlertMetaField,
		param.VendorConfig,
		EnhanceExtensionsWithHostname(param.Hostname),
		EnhanceExtensionsWithAlertMeta(alert.AlertMetaField),
		EnhanceExtensionsFromIpsFields(alert.IpsFields, param.VendorConfig.Abbreviation),
	)
}

func (alert *IpsAlert) ToSyslogRFC3164WithCef(param ToSyslogRFC3164WithCefParam) (string, error) {
	return SyslogRFC3164WithCef(alert, param)
}

func EnhanceExtensionsFromIpsFields(fields types.Ips, vendorAbbreviation string) ExtensionsPipeline {
	return func(extension map[string]string) error {
		if extension == nil {
			return ErrExtensionIsNil
		}

		if fields.UriQuery != nil {
			extension["cs6Label"] = "uri_query"
			extension["cs6"] = *fields.UriQuery
		}

		// handle standard cef fields
		if fields.Action != nil {
			extension["act"] = *fields.Action
		}
		if fields.App != nil {
			extension["app"] = *fields.App
		}
		if fields.Dest != nil {
			extension["dst"] = *fields.Dest
		}
		if fields.DestPort != nil {
			extension["dpt"] = *fields.DestPort
		}
		if fields.Src != nil {
			extension["src"] = *fields.Src
		}
		if fields.SrcPort != nil {
			extension["spt"] = *fields.SrcPort
		}
		if fields.UriPath != nil {
			extension["request"] = *fields.UriPath
		}

		// handle user defined fields
		if fields.Timestamp != nil {
			transformedKey, err := UserDefinedFieldName("@timestamp", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Timestamp
			}
		}
		if fields.Version != nil {
			transformedKey, err := UserDefinedFieldName("@version", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Version
			}
		}
		if fields.Id != nil {
			transformedKey, err := UserDefinedFieldName("_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Id
			}
		}
		if fields.Index != nil {
			transformedKey, err := UserDefinedFieldName("_index", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Index
			}
		}
		if fields.Act != nil {
			transformedKey, err := UserDefinedFieldName("act", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Act
			}
		}
		if fields.Category != nil {
			transformedKey, err := UserDefinedFieldName("category", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Category
			}
		}
		if fields.DateDay != nil {
			transformedKey, err := UserDefinedFieldName("date_day", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateDay
			}
		}
		if fields.DateHour != nil {
			transformedKey, err := UserDefinedFieldName("date_hour", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateHour
			}
		}
		if fields.DateMinute != nil {
			transformedKey, err := UserDefinedFieldName("date_minute", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMinute
			}
		}
		if fields.DateMonth != nil {
			transformedKey, err := UserDefinedFieldName("date_month", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMonth
			}
		}
		if fields.DateSecond != nil {
			transformedKey, err := UserDefinedFieldName("date_second", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateSecond
			}
		}
		if fields.DateYear != nil {
			transformedKey, err := UserDefinedFieldName("date_year", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateYear
			}
		}
		if fields.DestAsName != nil {
			transformedKey, err := UserDefinedFieldName("dest_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestAsName
			}
		}
		if fields.DestAsn != nil {
			transformedKey, err := UserDefinedFieldName("dest_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestAsn
			}
		}
		if fields.DestCountry != nil {
			transformedKey, err := UserDefinedFieldName("dest_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestCountry
			}
		}
		if fields.Domain != nil {
			transformedKey, err := UserDefinedFieldName("domain", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Domain
			}
		}
		if fields.Fingerprint != nil {
			transformedKey, err := UserDefinedFieldName("fingerprint", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Fingerprint
			}
		}
		if fields.HostIp != nil {
			transformedKey, err := UserDefinedFieldName("host_ip", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostIp
			}
		}
		if fields.HostName != nil {
			transformedKey, err := UserDefinedFieldName("host_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostName
			}
		}
		if fields.ProjectId != nil {
			transformedKey, err := UserDefinedFieldName("project_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ProjectId
			}
		}
		if fields.SessionId != nil {
			transformedKey, err := UserDefinedFieldName("session_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SessionId
			}
		}
		if fields.Severity != nil {
			transformedKey, err := UserDefinedFieldName("severity", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Severity
			}
		}
		if fields.Signature != nil {
			transformedKey, err := UserDefinedFieldName("signature", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Signature
			}
		}
		if fields.SrcAsName != nil {
			transformedKey, err := UserDefinedFieldName("src_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcAsName
			}
		}
		if fields.SrcAsn != nil {
			transformedKey, err := UserDefinedFieldName("src_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcAsn
			}
		}
		if fields.SrcCountry != nil {
			transformedKey, err := UserDefinedFieldName("src_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcCountry
			}
		}
		if fields.UriQuery != nil {
			transformedKey, err := UserDefinedFieldName("uri_query", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.UriQuery
			}
		}
		if fields.UserAgent != nil {
			transformedKey, err := UserDefinedFieldName("user_agent", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.UserAgent
			}
		}
		if fields.VendorProduct != nil {
			transformedKey, err := UserDefinedFieldName("vendor_product", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.VendorProduct
			}
		}

		return nil
	}
}
