// Code generated by github.com/reflective-technology/cybereyes-cef/v3/alert/codegen, DO NOT EDIT.
package alert_test

import (
	"testing"

	"github.com/reflective-technology/cybereyes-cef/v3/alert"
	"github.com/reflective-technology/cybereyes-cef/v3/types"
	"github.com/stretchr/testify/assert"
)

var testIpsAlert = alert.IpsAlert{
	AlertMetaField: testAlertMeta,
	IpsFields: types.Ips{
		Action:        new("test-value"),
		App:           new("test-value"),
		Dest:          new("test-value"),
		DestPort:      new("test-value"),
		Src:           new("test-value"),
		SrcPort:       new("test-value"),
		UriPath:       new("test-value"),
		Timestamp:     new("test-value"),
		Version:       new("test-value"),
		Id:            new("test-value"),
		Index:         new("test-value"),
		Act:           new("test-value"),
		Category:      new("test-value"),
		DateDay:       new("test-value"),
		DateHour:      new("test-value"),
		DateMinute:    new("test-value"),
		DateMonth:     new("test-value"),
		DateSecond:    new("test-value"),
		DateYear:      new("test-value"),
		DestAsName:    new("test-value"),
		DestAsn:       new("test-value"),
		DestCountry:   new("test-value"),
		Domain:        new("test-value"),
		Fingerprint:   new("test-value"),
		HostIp:        new("test-value"),
		HostName:      new("test-value"),
		ProjectId:     new("test-value"),
		SessionId:     new("test-value"),
		Severity:      new("test-value"),
		Signature:     new("test-value"),
		SrcAsName:     new("test-value"),
		SrcAsn:        new("test-value"),
		SrcCountry:    new("test-value"),
		UserAgent:     new("test-value"),
		VendorProduct: new("test-value"),
		UriQuery:      new("param=value"),
	},
}

func TestIpsAlert_ToCef(t *testing.T) {
	cef, err := testIpsAlert.ToCef(alert.ToCefParam{
		VendorConfig: alert.VendorReflective,
		Hostname:     "example.com",
	})
	assert.NoError(t, err)
	assert.NotEmpty(t, cef)
	t.Log(cef)
}
