// Code generated by github.com/reflective-technology/cybereyes-cef/alert/codegen, DO NOT EDIT.
package alert_test

import (
	"testing"

	"github.com/reflective-technology/cybereyes-cef/alert"
	"github.com/reflective-technology/cybereyes-cef/types"
	"github.com/stretchr/testify/assert"
)

var testSysmonWindowsAlert = alert.SysmonWindowsAlert{
	AlertMetaField: testAlertMeta,
	SysmonWindowsFields: types.SysmonWindows{
		ProcessId:               new("test-value"),
		ProcessName:             new("test-value"),
		ProcessPath:             new("test-value"),
		User:                    new("test-value"),
		Timestamp:               new("test-value"),
		Version:                 new("test-value"),
		Id:                      new("test-value"),
		Index:                   new("test-value"),
		Attack:                  new("test-value"),
		Cmdline:                 new("test-value"),
		DateDay:                 new("test-value"),
		DateHour:                new("test-value"),
		DateMinute:              new("test-value"),
		DateMonth:               new("test-value"),
		DateSecond:              new("test-value"),
		DateYear:                new("test-value"),
		Desc:                    new("test-value"),
		Ds:                      new("test-value"),
		EventId:                 new("test-value"),
		FileName:                new("test-value"),
		Fingerprint:             new("test-value"),
		HashesImphash:           new("test-value"),
		HashesMd5:               new("test-value"),
		HashesSha1:              new("test-value"),
		HashesSha256:            new("test-value"),
		HostIp:                  new("test-value"),
		HostName:                new("test-value"),
		Level:                   new("test-value"),
		OriginalFileName:        new("test-value"),
		ParentCmdline:           new("test-value"),
		ParentName:              new("test-value"),
		ParentProcessPath:       new("test-value"),
		ParentUser:              new("test-value"),
		ProcessCurrentDirectory: new("test-value"),
		ProjectId:               new("test-value"),
		RuleName:                new("test-value"),
		Tactic:                  new("test-value"),
		Technique:               new("test-value"),
	},
}

func TestSysmonWindowsAlert_ToCef(t *testing.T) {
	cef, err := testSysmonWindowsAlert.ToCef(alert.ToCefParam{
		VendorConfig: alert.VendorReflective,
		Hostname:     "example.com",
	})
	assert.NoError(t, err)
	assert.NotEmpty(t, cef)
	t.Log(cef)
}
