// Code generated by gitlab.tp.zuso.arpa/zuso-rd-team/go-pkg/events.git/alert/codegen, DO NOT EDIT.
package alert

import (
	"gitlab.tp.zuso.arpa/zuso-rd-team/go-pkg/events.git/types"
)

type WebAlert struct {
	AlertMetaField
	WebFields types.Web
}

func (alert *WebAlert) ToCef(param ToCefParam) (string, error) {
	return ResolveCef(
		alert.AlertMetaField,
		param.VendorConfig,
		EnhanceExtensionsWithHostname(param.Hostname),
		EnhanceExtensionsWithAlertMeta(alert.AlertMetaField),
		EnhanceExtensionsFromWebFields(alert.WebFields, param.VendorConfig.Abbreviation),
	)
}

func (alert *WebAlert) ToSyslogRFC3164WithCef(param ToSyslogRFC3164WithCefParam) (string, error) {
	return SyslogRFC3164WithCef(alert, param)
}

func EnhanceExtensionsFromWebFields(fields types.Web, vendorAbbreviation string) ExtensionsPipeline {
	return func(extension map[string]string) error {
		if extension == nil {
			return ErrExtensionIsNil
		}

		if fields.Action != nil {
			extension["act"] = *fields.Action
		}

		if fields.BytesIn != nil {
			extension["in"] = *fields.BytesIn
		}

		if fields.BytesOut != nil {
			extension["out"] = *fields.BytesOut
		}

		if fields.Cookie != nil {
			extension["requestCookies"] = *fields.Cookie
		}

		if fields.Dest != nil {
			extension["dst"] = *fields.Dest
		}

		if fields.DestPort != nil {
			extension["dpt"] = *fields.DestPort
		}

		if fields.HttpMethod != nil {
			extension["requestMethod"] = *fields.HttpMethod
		}

		if fields.HttpReferrer != nil {
			extension["requestContext"] = *fields.HttpReferrer
		}

		if fields.HttpUserAgent != nil {
			extension["requestClientApplication"] = *fields.HttpUserAgent
		}

		if fields.Src != nil {
			extension["src"] = *fields.Src
		}

		if fields.SrcPort != nil {
			extension["spt"] = *fields.SrcPort
		}

		if fields.UriPath != nil {
			extension["request"] = *fields.UriPath
		}

		if fields.UrlDomain != nil {
			extension["dhost"] = *fields.UrlDomain
		}

		if fields.User != nil {
			extension["suser"] = *fields.User
		}

		if fields.Timestamp != nil {
			transformedKey, err := UserDefinedFieldName("@timestamp", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Timestamp
			}
		}

		if fields.Version != nil {
			transformedKey, err := UserDefinedFieldName("@version", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Version
			}
		}

		if fields.Id != nil {
			transformedKey, err := UserDefinedFieldName("_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Id
			}
		}

		if fields.Index != nil {
			transformedKey, err := UserDefinedFieldName("_index", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Index
			}
		}

		if fields.Act != nil {
			transformedKey, err := UserDefinedFieldName("act", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Act
			}
		}

		if fields.BodyBytesOut != nil {
			transformedKey, err := UserDefinedFieldName("body_bytes_out", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.BodyBytesOut
			}
		}

		if fields.DateDay != nil {
			transformedKey, err := UserDefinedFieldName("date_day", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateDay
			}
		}

		if fields.DateHour != nil {
			transformedKey, err := UserDefinedFieldName("date_hour", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateHour
			}
		}

		if fields.DateMinute != nil {
			transformedKey, err := UserDefinedFieldName("date_minute", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMinute
			}
		}

		if fields.DateMonth != nil {
			transformedKey, err := UserDefinedFieldName("date_month", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMonth
			}
		}

		if fields.DateSecond != nil {
			transformedKey, err := UserDefinedFieldName("date_second", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateSecond
			}
		}

		if fields.DateYear != nil {
			transformedKey, err := UserDefinedFieldName("date_year", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateYear
			}
		}

		if fields.DestAsName != nil {
			transformedKey, err := UserDefinedFieldName("dest_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestAsName
			}
		}

		if fields.DestAsn != nil {
			transformedKey, err := UserDefinedFieldName("dest_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestAsn
			}
		}

		if fields.DestCountry != nil {
			transformedKey, err := UserDefinedFieldName("dest_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestCountry
			}
		}

		if fields.Duration != nil {
			transformedKey, err := UserDefinedFieldName("duration", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Duration
			}
		}

		if fields.FileExtension != nil {
			transformedKey, err := UserDefinedFieldName("file_extension", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.FileExtension
			}
		}

		if fields.Fingerprint != nil {
			transformedKey, err := UserDefinedFieldName("fingerprint", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Fingerprint
			}
		}

		if fields.HostIp != nil {
			transformedKey, err := UserDefinedFieldName("host_ip", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostIp
			}
		}

		if fields.HostName != nil {
			transformedKey, err := UserDefinedFieldName("host_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostName
			}
		}

		if fields.HttpReferrerDomain != nil {
			transformedKey, err := UserDefinedFieldName("http_referrer_domain", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HttpReferrerDomain
			}
		}

		if fields.OriginalSrc != nil {
			transformedKey, err := UserDefinedFieldName("original_src", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrc
			}
		}

		if fields.OriginalSrcAsName != nil {
			transformedKey, err := UserDefinedFieldName("original_src_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrcAsName
			}
		}

		if fields.OriginalSrcAsn != nil {
			transformedKey, err := UserDefinedFieldName("original_src_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrcAsn
			}
		}

		if fields.OriginalSrcCountry != nil {
			transformedKey, err := UserDefinedFieldName("original_src_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrcCountry
			}
		}

		if fields.ProjectId != nil {
			transformedKey, err := UserDefinedFieldName("project_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ProjectId
			}
		}

		if fields.Realip != nil {
			transformedKey, err := UserDefinedFieldName("realip", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Realip
			}
		}

		if fields.RealipAsName != nil {
			transformedKey, err := UserDefinedFieldName("realip_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RealipAsName
			}
		}

		if fields.RealipAsn != nil {
			transformedKey, err := UserDefinedFieldName("realip_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RealipAsn
			}
		}

		if fields.RealipCountry != nil {
			transformedKey, err := UserDefinedFieldName("realip_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RealipCountry
			}
		}

		if fields.SendContentType != nil {
			transformedKey, err := UserDefinedFieldName("send_content_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SendContentType
			}
		}

		if fields.Site != nil {
			transformedKey, err := UserDefinedFieldName("site", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Site
			}
		}

		if fields.SrcAsName != nil {
			transformedKey, err := UserDefinedFieldName("src_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcAsName
			}
		}

		if fields.SrcAsn != nil {
			transformedKey, err := UserDefinedFieldName("src_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcAsn
			}
		}

		if fields.SrcCountry != nil {
			transformedKey, err := UserDefinedFieldName("src_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcCountry
			}
		}

		if fields.Status != nil {
			transformedKey, err := UserDefinedFieldName("status", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Status
			}
		}

		if fields.UriQuery != nil {
			transformedKey, err := UserDefinedFieldName("uri_query", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.UriQuery
			}
		}

		if fields.VendorProduct != nil {
			transformedKey, err := UserDefinedFieldName("vendor_product", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.VendorProduct
			}
		}

		if fields.XForwardFor != nil {
			transformedKey, err := UserDefinedFieldName("x_forward_for", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.XForwardFor
			}
		}

		return nil
	}
}
