// Code generated by github.com/reflective-technology/cybereyes-cef/v3/alert/codegen, DO NOT EDIT.
package alert

import (
	"github.com/reflective-technology/cybereyes-cef/v3/types"
)

type WebApplicationFirewallAlert struct {
	AlertMetaField
	WebApplicationFirewallFields types.WebApplicationFirewall
}

func (alert *WebApplicationFirewallAlert) ToCef(param ToCefParam) (string, error) {
	return ResolveCef(
		alert.AlertMetaField,
		param.VendorConfig,
		EnhanceExtensionsWithHostname(param.Hostname),
		EnhanceExtensionsWithAlertMeta(alert.AlertMetaField),
		EnhanceExtensionsFromWebApplicationFirewallFields(alert.WebApplicationFirewallFields, param.VendorConfig.Abbreviation),
	)
}

func (alert *WebApplicationFirewallAlert) ToSyslogRFC3164WithCef(param ToSyslogRFC3164WithCefParam) (string, error) {
	return SyslogRFC3164WithCef(alert, param)
}

func EnhanceExtensionsFromWebApplicationFirewallFields(fields types.WebApplicationFirewall, vendorAbbreviation string) ExtensionsPipeline {
	return func(extension map[string]string) error {
		if extension == nil {
			return ErrExtensionIsNil
		}

		if fields.Status != nil {
			extension["cs5Label"] = "status"
			extension["cs5"] = *fields.Status
		}

		if fields.UriQuery != nil {
			extension["cs6Label"] = "uri_query"
			extension["cs6"] = *fields.UriQuery
		}

		// handle standard cef fields
		if fields.Action != nil {
			extension["act"] = *fields.Action
		}
		if fields.App != nil {
			extension["app"] = *fields.App
		}
		if fields.BytesIn != nil {
			extension["in"] = *fields.BytesIn
		}
		if fields.BytesOut != nil {
			extension["out"] = *fields.BytesOut
		}
		if fields.Cookie != nil {
			extension["requestCookies"] = *fields.Cookie
		}
		if fields.Dest != nil {
			extension["dst"] = *fields.Dest
		}
		if fields.DestPort != nil {
			extension["dpt"] = *fields.DestPort
		}
		if fields.HttpMethod != nil {
			extension["requestMethod"] = *fields.HttpMethod
		}
		if fields.HttpReferrer != nil {
			extension["requestContext"] = *fields.HttpReferrer
		}
		if fields.HttpUserAgent != nil {
			extension["requestClientApplication"] = *fields.HttpUserAgent
		}
		if fields.Src != nil {
			extension["src"] = *fields.Src
		}
		if fields.SrcPort != nil {
			extension["spt"] = *fields.SrcPort
		}
		if fields.UriPath != nil {
			extension["request"] = *fields.UriPath
		}
		if fields.UrlDomain != nil {
			extension["dhost"] = *fields.UrlDomain
		}
		if fields.User != nil {
			extension["suser"] = *fields.User
		}

		// handle user defined fields
		if fields.Timestamp != nil {
			transformedKey, err := UserDefinedFieldName("@timestamp", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Timestamp
			}
		}
		if fields.Version != nil {
			transformedKey, err := UserDefinedFieldName("@version", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Version
			}
		}
		if fields.Id != nil {
			transformedKey, err := UserDefinedFieldName("_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Id
			}
		}
		if fields.Index != nil {
			transformedKey, err := UserDefinedFieldName("_index", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Index
			}
		}
		if fields.BodyBytesOut != nil {
			transformedKey, err := UserDefinedFieldName("body_bytes_out", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.BodyBytesOut
			}
		}
		if fields.Category != nil {
			transformedKey, err := UserDefinedFieldName("category", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Category
			}
		}
		if fields.DateDay != nil {
			transformedKey, err := UserDefinedFieldName("date_day", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateDay
			}
		}
		if fields.DateHour != nil {
			transformedKey, err := UserDefinedFieldName("date_hour", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateHour
			}
		}
		if fields.DateMinute != nil {
			transformedKey, err := UserDefinedFieldName("date_minute", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMinute
			}
		}
		if fields.DateMonth != nil {
			transformedKey, err := UserDefinedFieldName("date_month", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMonth
			}
		}
		if fields.DateSecond != nil {
			transformedKey, err := UserDefinedFieldName("date_second", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateSecond
			}
		}
		if fields.DateYear != nil {
			transformedKey, err := UserDefinedFieldName("date_year", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateYear
			}
		}
		if fields.DestAsName != nil {
			transformedKey, err := UserDefinedFieldName("dest_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestAsName
			}
		}
		if fields.DestAsn != nil {
			transformedKey, err := UserDefinedFieldName("dest_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestAsn
			}
		}
		if fields.DestCountry != nil {
			transformedKey, err := UserDefinedFieldName("dest_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DestCountry
			}
		}
		if fields.Duration != nil {
			transformedKey, err := UserDefinedFieldName("duration", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Duration
			}
		}
		if fields.FileExtension != nil {
			transformedKey, err := UserDefinedFieldName("file_extension", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.FileExtension
			}
		}
		if fields.Fingerprint != nil {
			transformedKey, err := UserDefinedFieldName("fingerprint", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Fingerprint
			}
		}
		if fields.FullRequest != nil {
			transformedKey, err := UserDefinedFieldName("full_request", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.FullRequest
			}
		}
		if fields.Host != nil {
			transformedKey, err := UserDefinedFieldName("host", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Host
			}
		}
		if fields.HostIp != nil {
			transformedKey, err := UserDefinedFieldName("host_ip", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostIp
			}
		}
		if fields.HostName != nil {
			transformedKey, err := UserDefinedFieldName("host_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostName
			}
		}
		if fields.HttpAccept != nil {
			transformedKey, err := UserDefinedFieldName("http_accept", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HttpAccept
			}
		}
		if fields.HttpClassName != nil {
			transformedKey, err := UserDefinedFieldName("http_class_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HttpClassName
			}
		}
		if fields.HttpReferrerDomain != nil {
			transformedKey, err := UserDefinedFieldName("http_referrer_domain", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HttpReferrerDomain
			}
		}
		if fields.MatchedPattern != nil {
			transformedKey, err := UserDefinedFieldName("matched_pattern", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.MatchedPattern
			}
		}
		if fields.OriginalSrc != nil {
			transformedKey, err := UserDefinedFieldName("original_src", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrc
			}
		}
		if fields.OriginalSrcAsName != nil {
			transformedKey, err := UserDefinedFieldName("original_src_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrcAsName
			}
		}
		if fields.OriginalSrcAsn != nil {
			transformedKey, err := UserDefinedFieldName("original_src_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrcAsn
			}
		}
		if fields.OriginalSrcCountry != nil {
			transformedKey, err := UserDefinedFieldName("original_src_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.OriginalSrcCountry
			}
		}
		if fields.PolicyName != nil {
			transformedKey, err := UserDefinedFieldName("policy_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.PolicyName
			}
		}
		if fields.ProjectId != nil {
			transformedKey, err := UserDefinedFieldName("project_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ProjectId
			}
		}
		if fields.Realip != nil {
			transformedKey, err := UserDefinedFieldName("realip", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Realip
			}
		}
		if fields.RealipAsName != nil {
			transformedKey, err := UserDefinedFieldName("realip_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RealipAsName
			}
		}
		if fields.RealipAsn != nil {
			transformedKey, err := UserDefinedFieldName("realip_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RealipAsn
			}
		}
		if fields.RealipCountry != nil {
			transformedKey, err := UserDefinedFieldName("realip_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RealipCountry
			}
		}
		if fields.Referer != nil {
			transformedKey, err := UserDefinedFieldName("referer", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Referer
			}
		}
		if fields.RequestConnection != nil {
			transformedKey, err := UserDefinedFieldName("request_connection", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RequestConnection
			}
		}
		if fields.RequestContentLength != nil {
			transformedKey, err := UserDefinedFieldName("request_content_length", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RequestContentLength
			}
		}
		if fields.RequestContentType != nil {
			transformedKey, err := UserDefinedFieldName("request_content_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.RequestContentType
			}
		}
		if fields.ResponseContentType != nil {
			transformedKey, err := UserDefinedFieldName("response_content_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ResponseContentType
			}
		}
		if fields.SendContentType != nil {
			transformedKey, err := UserDefinedFieldName("send_content_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SendContentType
			}
		}
		if fields.Severity != nil {
			transformedKey, err := UserDefinedFieldName("severity", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Severity
			}
		}
		if fields.Signature != nil {
			transformedKey, err := UserDefinedFieldName("signature", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Signature
			}
		}
		if fields.Site != nil {
			transformedKey, err := UserDefinedFieldName("site", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Site
			}
		}
		if fields.SrcAsName != nil {
			transformedKey, err := UserDefinedFieldName("src_as_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcAsName
			}
		}
		if fields.SrcAsn != nil {
			transformedKey, err := UserDefinedFieldName("src_asn", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcAsn
			}
		}
		if fields.SrcCountry != nil {
			transformedKey, err := UserDefinedFieldName("src_country", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcCountry
			}
		}
		if fields.UserAgent != nil {
			transformedKey, err := UserDefinedFieldName("user-agent", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.UserAgent
			}
		}
		if fields.XForwardFor != nil {
			transformedKey, err := UserDefinedFieldName("x_forward_for", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.XForwardFor
			}
		}

		return nil
	}
}
