// Code generated by github.com/reflective-technology/cybereyes-cef/v3/alert/codegen, DO NOT EDIT.
package alert_test

import (
	"testing"

	"github.com/reflective-technology/cybereyes-cef/v3/alert"
	"github.com/reflective-technology/cybereyes-cef/v3/types"
	"github.com/stretchr/testify/assert"
)

var testWebAlert = alert.WebAlert{
	AlertMetaField: testAlertMeta,
	WebFields: types.Web{
		Action:               new("test-value"),
		BytesIn:              new("test-value"),
		BytesOut:             new("test-value"),
		Cookie:               new("test-value"),
		Dest:                 new("test-value"),
		DestPort:             new("test-value"),
		HttpMethod:           new("test-value"),
		HttpReferrer:         new("test-value"),
		HttpUserAgent:        new("test-value"),
		Src:                  new("test-value"),
		SrcPort:              new("test-value"),
		UriPath:              new("test-value"),
		UrlDomain:            new("test-value"),
		User:                 new("test-value"),
		Timestamp:            new("test-value"),
		Version:              new("test-value"),
		Id:                   new("test-value"),
		Index:                new("test-value"),
		Act:                  new("test-value"),
		BodyBytesOut:         new("test-value"),
		DateDay:              new("test-value"),
		DateHour:             new("test-value"),
		DateMinute:           new("test-value"),
		DateMonth:            new("test-value"),
		DateSecond:           new("test-value"),
		DateYear:             new("test-value"),
		DestAsName:           new("test-value"),
		DestAsn:              new("test-value"),
		DestCountry:          new("test-value"),
		Duration:             new("test-value"),
		FileExtension:        new("test-value"),
		Fingerprint:          new("test-value"),
		HostIp:               new("test-value"),
		HostName:             new("test-value"),
		HttpAccept:           new("test-value"),
		HttpReferrerDomain:   new("test-value"),
		OriginalSrc:          new("test-value"),
		OriginalSrcAsName:    new("test-value"),
		OriginalSrcAsn:       new("test-value"),
		OriginalSrcCountry:   new("test-value"),
		ProjectId:            new("test-value"),
		Realip:               new("test-value"),
		RealipAsName:         new("test-value"),
		RealipAsn:            new("test-value"),
		RealipCountry:        new("test-value"),
		RequestConnection:    new("test-value"),
		RequestContentLength: new("test-value"),
		RequestContentType:   new("test-value"),
		ResponseContentType:  new("test-value"),
		SendContentType:      new("test-value"),
		Site:                 new("test-value"),
		SrcAsName:            new("test-value"),
		SrcAsn:               new("test-value"),
		SrcCountry:           new("test-value"),
		VendorProduct:        new("test-value"),
		XForwardFor:          new("test-value"),
		Status:               new("200"),
		UriQuery:             new("param=value"),
	},
}

func TestWebAlert_ToCef(t *testing.T) {
	cef, err := testWebAlert.ToCef(alert.ToCefParam{
		VendorConfig: alert.VendorReflective,
		Hostname:     "example.com",
	})
	assert.NoError(t, err)
	assert.NotEmpty(t, cef)
	t.Log(cef)
}
