// Code generated by github.com/reflective-technology/cybereyes-cef/v3/alert/codegen, DO NOT EDIT.
package alert_test

import (
	"testing"

	"github.com/go-openapi/testify/v2/assert"
	"github.com/reflective-technology/cybereyes-cef/v3/alert"
	"github.com/reflective-technology/cybereyes-cef/v3/types"
)

var testWindowsEventsApplicationAlert = alert.WindowsEventsApplicationAlert{
	AlertMetaField: testAlertMeta,
	WindowsEventsApplicationFields: types.WindowsEventsApplication{
		Timestamp:          new("test-value"),
		Version:            new("test-value"),
		Id:                 new("test-value"),
		Index:              new("test-value"),
		ApplicationMessage: new("test-value"),
		DateDay:            new("test-value"),
		DateHour:           new("test-value"),
		DateMinute:         new("test-value"),
		DateMonth:          new("test-value"),
		DateSecond:         new("test-value"),
		DateYear:           new("test-value"),
		EventCategory:      new("test-value"),
		EventId:            new("test-value"),
		Fingerprint:        new("test-value"),
		HostIp:             new("test-value"),
		HostName:           new("test-value"),
		ProjectId:          new("test-value"),
		Severity:           new("test-value"),
		SeverityValue:      new("test-value"),
	},
}

func TestWindowsEventsApplicationAlert_ToCef(t *testing.T) {
	cef, err := testWindowsEventsApplicationAlert.ToCef(alert.ToCefParam{
		VendorConfig: alert.VendorReflective,
		Hostname:     "example.com",
	})
	assert.NoError(t, err)
	assert.NotEmpty(t, cef)
	t.Log(cef)
}
