// Code generated by github.com/reflective-technology/cybereyes-cef/v3/alert/codegen, DO NOT EDIT.
package alert_test

import (
	"testing"

	"github.com/go-openapi/testify/v2/assert"
	"github.com/reflective-technology/cybereyes-cef/v3/alert"
	"github.com/reflective-technology/cybereyes-cef/v3/types"
)

var testWindowsEventsSecurityAlert = alert.WindowsEventsSecurityAlert{
	AlertMetaField: testAlertMeta,
	WindowsEventsSecurityFields: types.WindowsEventsSecurity{
		ProcessId:         new("test-value"),
		ProcessName:       new("test-value"),
		ProcessPath:       new("test-value"),
		Src:               new("test-value"),
		User:              new("test-value"),
		Timestamp:         new("test-value"),
		Version:           new("test-value"),
		Id:                new("test-value"),
		Index:             new("test-value"),
		AccountDomain:     new("test-value"),
		AccountName:       new("test-value"),
		ApplicationPath:   new("test-value"),
		Cmdline:           new("test-value"),
		DateDay:           new("test-value"),
		DateHour:          new("test-value"),
		DateMinute:        new("test-value"),
		DateMonth:         new("test-value"),
		DateSecond:        new("test-value"),
		DateYear:          new("test-value"),
		EventCategory:     new("test-value"),
		EventId:           new("test-value"),
		Fingerprint:       new("test-value"),
		HostIp:            new("test-value"),
		HostName:          new("test-value"),
		LogonProcessName:  new("test-value"),
		LogonProcessType:  new("test-value"),
		NewProcessId:      new("test-value"),
		NewProcessPath:    new("test-value"),
		ParentProcessPath: new("test-value"),
		ProjectId:         new("test-value"),
		ServiceName:       new("test-value"),
		ServiceStartType:  new("test-value"),
		ServiceType:       new("test-value"),
		SrcHostName:       new("test-value"),
		TargetDomainName:  new("test-value"),
	},
}

func TestWindowsEventsSecurityAlert_ToCef(t *testing.T) {
	cef, err := testWindowsEventsSecurityAlert.ToCef(alert.ToCefParam{
		VendorConfig: alert.VendorReflective,
		Hostname:     "example.com",
	})
	assert.NoError(t, err)
	assert.NotEmpty(t, cef)
	t.Log(cef)
}
