// Code generated by github.com/reflective-technology/cybereyes-cef/alert/codegen, DO NOT EDIT.
package alert

import (
	"github.com/reflective-technology/cybereyes-cef/types"
)

type WindowsEventsSecurityAlert struct {
	AlertMetaField
	WindowsEventsSecurityFields types.WindowsEventsSecurity
}

func (alert *WindowsEventsSecurityAlert) ToCef(param ToCefParam) (string, error) {
	return ResolveCef(
		alert.AlertMetaField,
		param.VendorConfig,
		EnhanceExtensionsWithHostname(param.Hostname),
		EnhanceExtensionsWithAlertMeta(alert.AlertMetaField),
		EnhanceExtensionsFromWindowsEventsSecurityFields(alert.WindowsEventsSecurityFields, param.VendorConfig.Abbreviation),
	)
}

func (alert *WindowsEventsSecurityAlert) ToSyslogRFC3164WithCef(param ToSyslogRFC3164WithCefParam) (string, error) {
	return SyslogRFC3164WithCef(alert, param)
}

func EnhanceExtensionsFromWindowsEventsSecurityFields(fields types.WindowsEventsSecurity, vendorAbbreviation string) ExtensionsPipeline {
	return func(extension map[string]string) error {
		if extension == nil {
			return ErrExtensionIsNil
		}

		// handle standard cef fields
		if fields.ProcessId != nil {
			extension["spid"] = *fields.ProcessId
		}
		if fields.ProcessName != nil {
			extension["sproc"] = *fields.ProcessName
		}
		if fields.ProcessPath != nil {
			extension["filePath"] = *fields.ProcessPath
		}
		if fields.Src != nil {
			extension["src"] = *fields.Src
		}
		if fields.User != nil {
			extension["suser"] = *fields.User
		}

		// handle user defined fields
		if fields.Timestamp != nil {
			transformedKey, err := UserDefinedFieldName("@timestamp", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Timestamp
			}
		}
		if fields.Version != nil {
			transformedKey, err := UserDefinedFieldName("@version", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Version
			}
		}
		if fields.Id != nil {
			transformedKey, err := UserDefinedFieldName("_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Id
			}
		}
		if fields.Index != nil {
			transformedKey, err := UserDefinedFieldName("_index", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Index
			}
		}
		if fields.AccountDomain != nil {
			transformedKey, err := UserDefinedFieldName("account_domain", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.AccountDomain
			}
		}
		if fields.AccountName != nil {
			transformedKey, err := UserDefinedFieldName("account_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.AccountName
			}
		}
		if fields.ApplicationPath != nil {
			transformedKey, err := UserDefinedFieldName("application_path", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ApplicationPath
			}
		}
		if fields.Cmdline != nil {
			transformedKey, err := UserDefinedFieldName("cmdline", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Cmdline
			}
		}
		if fields.DateDay != nil {
			transformedKey, err := UserDefinedFieldName("date_day", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateDay
			}
		}
		if fields.DateHour != nil {
			transformedKey, err := UserDefinedFieldName("date_hour", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateHour
			}
		}
		if fields.DateMinute != nil {
			transformedKey, err := UserDefinedFieldName("date_minute", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMinute
			}
		}
		if fields.DateMonth != nil {
			transformedKey, err := UserDefinedFieldName("date_month", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateMonth
			}
		}
		if fields.DateSecond != nil {
			transformedKey, err := UserDefinedFieldName("date_second", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateSecond
			}
		}
		if fields.DateYear != nil {
			transformedKey, err := UserDefinedFieldName("date_year", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.DateYear
			}
		}
		if fields.EventCategory != nil {
			transformedKey, err := UserDefinedFieldName("event_category", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.EventCategory
			}
		}
		if fields.EventId != nil {
			transformedKey, err := UserDefinedFieldName("event_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.EventId
			}
		}
		if fields.Fingerprint != nil {
			transformedKey, err := UserDefinedFieldName("fingerprint", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.Fingerprint
			}
		}
		if fields.HostIp != nil {
			transformedKey, err := UserDefinedFieldName("host_ip", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostIp
			}
		}
		if fields.HostName != nil {
			transformedKey, err := UserDefinedFieldName("host_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.HostName
			}
		}
		if fields.LogonProcessName != nil {
			transformedKey, err := UserDefinedFieldName("logon_process_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.LogonProcessName
			}
		}
		if fields.LogonProcessType != nil {
			transformedKey, err := UserDefinedFieldName("logon_process_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.LogonProcessType
			}
		}
		if fields.NewProcessId != nil {
			transformedKey, err := UserDefinedFieldName("new_process_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.NewProcessId
			}
		}
		if fields.NewProcessPath != nil {
			transformedKey, err := UserDefinedFieldName("new_process_path", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.NewProcessPath
			}
		}
		if fields.ParentProcessPath != nil {
			transformedKey, err := UserDefinedFieldName("parent_process_path", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ParentProcessPath
			}
		}
		if fields.ProjectId != nil {
			transformedKey, err := UserDefinedFieldName("project_id", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ProjectId
			}
		}
		if fields.ServiceName != nil {
			transformedKey, err := UserDefinedFieldName("service_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ServiceName
			}
		}
		if fields.ServiceStartType != nil {
			transformedKey, err := UserDefinedFieldName("service_start_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ServiceStartType
			}
		}
		if fields.ServiceType != nil {
			transformedKey, err := UserDefinedFieldName("service_type", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.ServiceType
			}
		}
		if fields.SrcHostName != nil {
			transformedKey, err := UserDefinedFieldName("src_host_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.SrcHostName
			}
		}
		if fields.TargetDomainName != nil {
			transformedKey, err := UserDefinedFieldName("target_domain_name", vendorAbbreviation)
			if err == nil {
				extension[transformedKey] = *fields.TargetDomainName
			}
		}

		return nil
	}
}
